/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_lanjutan;

import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class cobacoba extends javax.swing.JFrame {

    /**
     * Creates new form cobacoba
     */
    public cobacoba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Laki = new javax.swing.JRadioButton();
        Cewek = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TA1 = new javax.swing.JTextField();
        TA2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 150, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 41, 20);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 45, 20);

        jLabel4.setText("Berat badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 120, 20);
        getContentPane().add(Nama);
        Nama.setBounds(130, 50, 190, 26);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        getContentPane().add(Tinggi);
        Tinggi.setBounds(130, 90, 80, 26);
        getContentPane().add(Berat);
        Berat.setBounds(130, 140, 80, 26);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 190, 120, 20);

        buttonGroup1.add(Laki);
        Laki.setText("laki-laki");
        getContentPane().add(Laki);
        Laki.setBounds(150, 190, 87, 29);

        buttonGroup1.add(Cewek);
        Cewek.setText("perempuan");
        getContentPane().add(Cewek);
        Cewek.setBounds(250, 190, 133, 29);

        jButton1.setText("hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 250, 90, 29);

        jButton2.setText("coba lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 250, 120, 29);

        jButton3.setText("keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 250, 75, 29);

        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 90, 21, 20);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 140, 17, 20);

        jLabel8.setText("berat badan ideal anda adalah ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 320, 260, 20);
        getContentPane().add(Ideal);
        Ideal.setBounds(240, 320, 90, 26);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 320, 51, 20);
        getContentPane().add(TA1);
        TA1.setBounds(30, 370, 400, 26);
        getContentPane().add(TA2);
        TA2.setBounds(30, 410, 400, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        String nama = Nama.getText();
        
        int tinggi = Integer.parseInt(Tinggi.getText());
        int berat = Integer.parseInt(Berat.getText());
        int ideal = 0;
         if(Laki.isSelected()){
             ideal = tinggi - 104;
         }
            
        else if(Cewek.isSelected()){
             ideal = tinggi - 100;
        }
           String s = String.valueOf(ideal);
           Ideal.getText();
        
        
        if(ideal < berat){
            Ideal.setText(s);
            TA1.setText("Maaf "+Nama.getText() +", Sepertinya Anda overWeight : (");
            TA2.setText("Banyaklah berolahraga dan hindari makanan berkolestrol");
        }else if(ideal > berat){
           Ideal.setText(s);
            TA1.setText("Maaf "+Nama.getText() + ", Sepertinya anda underweight :(");
            TA2.setText("Banyaklah mengkonsumsi makanan yang berkatbohidrat");
        }else {
            Ideal.setText(s);
            TA1.setText("Hallo "+Nama.getText()+", berat badan anda sudah ideal :)");
            TA2.setText("lanjutkan pola makan teratur dan gaya hidup sehat");
        }
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Kotak belum terisi semua" ,"Message",JOptionPane.INFORMATION_MESSAGE);
        
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        buttonGroup1.clearSelection();
        Laki.setSelected(false);
        Cewek.setSelected(false);
        TA1.setText("");
        TA2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cobacoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cobacoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cobacoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cobacoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cobacoba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JRadioButton Cewek;
    private javax.swing.JTextField Ideal;
    private javax.swing.JRadioButton Laki;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField TA1;
    private javax.swing.JTextField TA2;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
