/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_lanjutan;

import javax.swing.JOptionPane;


/**
 *
 * @author WINDOWS 10
 */
public class latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form latihan3
     */
    public latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        Volume = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Volume2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 350, 20);

        jPanel2.setLayout(null);

        jLabel2.setText("Masukkan panjang :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 20, 190, 20);

        jLabel3.setText("Masukkan Lebar :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 60, 160, 20);

        jLabel4.setText("Masukkan tinggi :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 100, 160, 20);
        jPanel2.add(Panjang);
        Panjang.setBounds(220, 20, 160, 26);
        jPanel2.add(Lebar);
        Lebar.setBounds(220, 60, 160, 26);
        jPanel2.add(Tinggi);
        Tinggi.setBounds(220, 100, 160, 26);

        jLabel5.setText("cm");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(390, 20, 21, 20);

        jLabel6.setText("cm");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(390, 60, 21, 20);

        jLabel7.setText("cm");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(390, 100, 21, 20);

        Hitung.setText("hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel2.add(Hitung);
        Hitung.setBounds(180, 160, 77, 29);

        jTabbedPane1.addTab("BALOK", jPanel2);

        jPanel3.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 10, 190, 40);
        jPanel3.add(Sisi);
        Sisi.setBounds(30, 50, 170, 26);

        Volume.setText("volume");
        Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeActionPerformed(evt);
            }
        });
        jPanel3.add(Volume);
        Volume.setBounds(70, 90, 85, 29);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(210, 50, 60, 20);

        jTabbedPane1.addTab("KUBUS", jPanel3);

        jPanel4.setLayout(null);

        jLabel9.setText("Masukkan Panjang Jari-jari");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 20, 200, 20);
        jPanel4.add(Jari);
        Jari.setBounds(50, 50, 150, 26);

        jLabel10.setText("cm");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(210, 50, 60, 20);

        Volume2.setText("volume");
        Volume2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volume2ActionPerformed(evt);
            }
        });
        jPanel4.add(Volume2);
        Volume2.setBounds(70, 100, 93, 29);

        jTabbedPane1.addTab("BOLA", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 470, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        
        int panjang,lebar,tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi= Integer.parseInt(Tinggi.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume balok adalah : "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Error :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_HitungActionPerformed

    private void VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int volume = sisi*sisi*sisi;
        try {
            JOptionPane.showMessageDialog(null,"Luas permukaan kubus adalah :"+volume,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
        JOptionPane.showMessageDialog(null,"error :"+e, "Gagal",JOptionPane.WARNING_MESSAGE);
        
    }
    }//GEN-LAST:event_VolumeActionPerformed

    private void Volume2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volume2ActionPerformed
        // TODO add your handling code here:
        float jari;
        jari=Integer.parseInt(Jari.getText());
        float hasil1=(float) (4/3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Luas permukaan bola adalah :"+hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
        JOptionPane.showMessageDialog(null,"error :"+e, "Gagal",JOptionPane.WARNING_MESSAGE);
        
    }
    }//GEN-LAST:event_Volume2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton Volume;
    private javax.swing.JButton Volume2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
