/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan;

/**
 *
 * @author WINDOWS 10
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Harga1 = new javax.swing.JTextField();
        Harga2 = new javax.swing.JTextField();
        Harga3 = new javax.swing.JTextField();
        Harga4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        OKE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 20, 210, 20);

        jLabel2.setText("HARGA 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 90, 80, 20);

        jLabel3.setText("HARGA 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 130, 70, 20);

        jLabel4.setText("HARGA 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 170, 80, 20);

        jLabel5.setText("HARGA 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 210, 80, 20);
        getContentPane().add(Harga1);
        Harga1.setBounds(270, 90, 300, 26);
        getContentPane().add(Harga2);
        Harga2.setBounds(270, 130, 300, 26);
        getContentPane().add(Harga3);
        Harga3.setBounds(270, 170, 300, 26);
        getContentPane().add(Harga4);
        Harga4.setBounds(270, 210, 300, 26);

        jLabel6.setText("DISKON");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 250, 80, 20);
        getContentPane().add(Diskon);
        Diskon.setBounds(270, 250, 300, 26);

        OKE.setText("PROSES");
        OKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKEActionPerformed(evt);
            }
        });
        getContentPane().add(OKE);
        OKE.setBounds(110, 330, 91, 29);

        DELETE.setText("HAPUS");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(DELETE);
        DELETE.setBounds(320, 330, 83, 29);

        EXIT.setText("KELUAR");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT);
        EXIT.setBounds(530, 330, 91, 29);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 400, 420, 200);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 740, 830);

        setBounds(0, 0, 758, 884);
    }// </editor-fold>//GEN-END:initComponents

    private void OKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKEActionPerformed
        // TODO add your handling code here:
        int harga1 = Integer.parseInt(Harga1.getText());
         int harga2 = Integer.parseInt(Harga2.getText());
          int harga3 = Integer.parseInt(Harga3.getText());
           int harga4 = Integer.parseInt(Harga4.getText());
           int total = harga1+harga2+harga3+harga4;
            int diskon = Integer.parseInt(Diskon.getText());
            int hasil = total*diskon/100;
            TextArea.setText("harga barang 1 : "+harga1+ "\n" + "Harga barang 2 : "+harga2+ "\n" +"Harga barang 3 :"+harga3+"\n"+"Harga barang 4 :"+harga4+"\n"+"Diskon anda :"+diskon+"\n"+
                    "Total Harga : "+total+"\n"+"Total bayar : "+hasil);
        
    }//GEN-LAST:event_OKEActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_EXITActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here
        TextArea.setText("");
        Harga1.setText("");
         Harga2.setText("");
          Harga3.setText("");
           Harga4.setText("");
           Diskon.setText("");
        
    }//GEN-LAST:event_DELETEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField Diskon;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField Harga1;
    private javax.swing.JTextField Harga2;
    private javax.swing.JTextField Harga3;
    private javax.swing.JTextField Harga4;
    private javax.swing.JButton OKE;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
