/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan;

/**
 *
 * @author WINDOWS 10
 */
public class latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form latihan4
     */
    public latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        jurusan2 = new javax.swing.JRadioButton();
        jurusan1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        hobi1 = new javax.swing.JCheckBox();
        hobi2 = new javax.swing.JCheckBox();
        hobi3 = new javax.swing.JCheckBox();
        hobi4 = new javax.swing.JCheckBox();
        Submit = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        TA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("BIODATA SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 250, 20);

        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 45, 20);

        jLabel3.setText("ABSEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 51, 20);

        jLabel4.setText("JURUSAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 80, 20);
        getContentPane().add(Nama);
        Nama.setBounds(150, 60, 240, 40);
        getContentPane().add(Absen);
        Absen.setBounds(150, 110, 240, 40);

        bgjurusan.add(jurusan2);
        jurusan2.setText("TKJ");
        getContentPane().add(jurusan2);
        jurusan2.setBounds(240, 170, 133, 29);

        bgjurusan.add(jurusan1);
        jurusan1.setText("RPL");
        getContentPane().add(jurusan1);
        jurusan1.setBounds(150, 170, 59, 29);

        jLabel5.setText("HOBI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 51, 20);

        hobi1.setText("Programming");
        getContentPane().add(hobi1);
        hobi1.setBounds(140, 220, 140, 29);

        hobi2.setText("Teknisi");
        getContentPane().add(hobi2);
        hobi2.setBounds(290, 220, 83, 29);

        hobi3.setText("Animator");
        getContentPane().add(hobi3);
        hobi3.setBounds(140, 270, 99, 29);

        hobi4.setText("Designer");
        getContentPane().add(hobi4);
        hobi4.setBounds(290, 270, 95, 29);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(80, 330, 83, 29);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(220, 330, 77, 29);

        Keluar.setText("keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(370, 330, 75, 29);
        getContentPane().add(TA);
        TA.setBounds(60, 430, 380, 170);

        jLabel6.setText("HASIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 390, 45, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 620);

        setBounds(0, 0, 641, 678);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan;
        String hobi="";
        //untuk jurusan
        if(jurusan1.isSelected())
            jurusan = "RPL";
        else if(jurusan2.isSelected());
        jurusan = "TKJ";
        
        //untuk hobi
        if(hobi1.isSelected())
            hobi+=hobi1.getText()+",";
        if(hobi2.isSelected())
            hobi+=hobi3.getText()+",";
        if(hobi3.isSelected())
            hobi+=hobi3.getText()+",";
        if(hobi4.isSelected())
            hobi+=hobi4.getText()+",";
        TA.setText("Nama siswa :"+nama+"\n"+"Absen Siswa : " +absen+"\n"+"Jurusan : "+jurusan+"\n"+"Hobi"+hobi);
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        TA.setText("");
        Nama.setText("");
        Absen.setText("");
        bgjurusan.clearSelection();
        hobi1.setSelected(false);
        hobi2.setSelected(false);
        hobi3.setSelected(false);
        hobi4.setSelected(false);
       
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
       dispose();
        // TODO add your handling code here:
        
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TA;
    private javax.swing.ButtonGroup bgjurusan;
    private javax.swing.JCheckBox hobi1;
    private javax.swing.JCheckBox hobi2;
    private javax.swing.JCheckBox hobi3;
    private javax.swing.JCheckBox hobi4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jurusan1;
    private javax.swing.JRadioButton jurusan2;
    // End of variables declaration//GEN-END:variables
}
